menu_items = [
    {
        "id": 1,
        "name": "Masala Chai",
        "category": "chai",
        "description": "A spiced tea made with black tea, milk, and a blend of aromatic spices.",
        "price": 30,
        "available": True,
    },
    {
        "id": 2,
        "name": "Ginger Chai",
        "category": "chai",
        "description": "A warming tea infused with fresh ginger for a spicy kick.",
        "price": 30,
        "available": True,
    },
    {
        "id": 3,
        "name": "Cardamom Chai",
        "category": "chai",
        "description": "A fragrant tea flavored with crushed green cardamom pods.",
        "price": 35,
        "available": True,
    },
    {
        "id": 4,
        "name": "Kashmiri Kahwa",
        "category": "chai",
        "description": "A delicate green tea brewed with saffron, cardamom, and almonds.",
        "price": 60,
        "available": True,
    },
    {
        "id": 5,
        "name": "Adrak Chai",
        "category": "chai",
        "description": "A robust black tea boiled with crushed ginger and jaggery.",
        "price": 35,
        "available": False,
    },
    {
        "id": 6,
        "name": "Tulsi Chai",
        "category": "chai",
        "description": "A soothing tea blended with holy basil leaves for added wellness.",
        "price": 35,
        "available": True,
    },
    {
        "id": 7,
        "name": "Lemon Grass Tea",
        "category": "herbal",
        "description": "A refreshing caffeine-free infusion made with fresh lemongrass.",
        "price": 40,
        "available": True,
    },
    {
        "id": 8,
        "name": "Kesar Chai",
        "category": "chai",
        "description": "A rich milk tea infused with saffron strands and a hint of sweetness.",
        "price": 65,
        "available": True,
    },
    {
        "id": 9,
        "name": "Black Coffee",
        "category": "coffee",
        "description": "A bold, unsweetened brew made from freshly ground coffee beans.",
        "price": 40,
        "available": True,
    },
    {
        "id": 10,
        "name": "Cold Coffee",
        "category": "coffee",
        "description": "A chilled, creamy coffee blended with milk and ice.",
        "price": 70,
        "available": False,
    },
    {
        "id": 11,
        "name": "Chamomile Tea",
        "category": "herbal",
        "description": "A calming caffeine-free tea made from dried chamomile flowers.",
        "price": 45,
        "available": True,
    },
]
