/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'

const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LessonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons': typeof LessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lessons' | '/lessons/$lessonId' | '/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lessons/$lessonId' | '/lessons'
  id: '__root__' | '/' | '/lessons' | '/lessons/$lessonId' | '/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonsRoute: typeof LessonsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof LessonsRoute
    }
  }
}

interface LessonsRouteChildren {
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  LessonsIndexRoute: LessonsIndexRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonsRoute: LessonsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
